language: objective-c
osx_image: xcode7.1

before_install:
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
    - pod repo update --silent

script:
    - pod lib lint
    - xctool -workspace AFWebViewController.xcworkspace -scheme 'AFWebViewController' -sdk iphonesimulator build
